repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args:
    - --maxkb=2048

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3.8


- repo: local
  hooks:
  - id: pytest
    name: pytest
    language: system
    entry: poetry run pytest
    pass_filenames: false
    stages:
    - push
